server:
  port: 7001
  servlet:
    context-path: /coupon-template

spring:
  application:
    name: eureka-client-coupon-template
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true

    open-in-view: false


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/imooc_coupon_data?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: ImoocCouponHikariCP

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
    register-with-eureka: true
    fetch-registry: true
#---------------------------------------------------------



management:
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: imooc-coupon-template
    groupId: imooc-coupon-service
    artifactId: coupon-template
    version: 0.0.1-SNAPSHOT


#-------------------------------------------------------------
logging:
  level:
    com.imooc.coupon: debug
