spring:
  application:
    name: coupon-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    #标识是否从eureka server中获取注册信息，单节点信息不需要同步其他节点数据，设置为false
    fetch-registry: false
    #是否将自己注册到eareka server 因为是单节点所以设置为false
    register-with-eureka: false
    #设置注册地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/